DEFAULT_AVATAR = 'http://bit.ly/defaultAvatar'
DEFAULT_THUMBNAIL = None
ZIP_THUMBNAIL = None
DOCX_THUMBNAIL = None
PDF_THUMBNAIL = None
SHEET_THUMBNAIL = None
SOUND_THUMBNAIL = None
TEXT_THUMBNAIL =  None