"""empty message

Revision ID: 13a8750c6839
Revises: e42ecabae6c5
Create Date: 2019-12-23 23:40:53.404551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13a8750c6839'
down_revision = 'e42ecabae6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('viewed', sa.Boolean(), nullable=False))
    op.drop_column('notifications', 'viewd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('viewd', mysql.VARCHAR(length=512), nullable=False))
    op.drop_column('notifications', 'viewed')
    # ### end Alembic commands ###
