"""empty message

Revision ID: 43913980daf3
Revises: a501d41e21bc
Create Date: 2019-10-04 18:48:14.074347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43913980daf3'
down_revision = 'a501d41e21bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('file_title', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
