"""empty message

Revision ID: 75ab5bc0acc0
Revises: a501d41e21bc
Create Date: 2019-10-05 09:47:44.317859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ab5bc0acc0'
down_revision = 'a501d41e21bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('file_title', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('trashed', sa.Boolean(), nullable=False),
    sa.Column('trashed_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
